name: Gradle Test Backend

on: [push, pull_request]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17

    - name: Navigate to Subfolder
      run: cd backend
      
    - name: Run Gradle Tests
      run: ./gradlew test
